#!/bin/bash
# Generate structured markdown from OpenRouter API
# Usage: ./scripts/generate-model-pricing.sh [API_KEY]

set -e

API_KEY="${1:-$OPENROUTER_API_KEY}"

if [ -z "$API_KEY" ]; then
    echo "Error: OpenRouter API key required"
    exit 1
fi

OUTPUT_FILE="OPENROUTER_MODELS.md"
TEMP_FILE=$(mktemp)

# Fetch all models
echo "Fetching OpenRouter models..." >&2
curl -s 'https://openrouter.ai/api/v1/models' \
    -H "Authorization: Bearer $API_KEY" > "$TEMP_FILE"

# Generate markdown
cat > "$OUTPUT_FILE" << 'HEADER'
# OpenRouter Models Pricing

**Auto-generated daily from OpenRouter API**

This file is automatically updated daily with current model pricing from OpenRouter.

HEADER

# Add timestamp
echo "**Last Updated:** $(date -u '+%Y-%m-%d %H:%M UTC')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Add summary
echo "## Quick Reference - Top Recommended Models" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "| Model | Input (per 1M) | Output (per 1M) | Context | Category |" >> "$OUTPUT_FILE"
echo "|-------|----------------|-----------------|---------|----------|" >> "$OUTPUT_FILE"

# Top recommended models  
jq -r '.data[] | 
    select(.id | test("kimi-k2.5|gpt-4o-mini|gpt-4o|claude-3.5-sonnet|gemini-pro-1.5")) |
    select(.pricing.prompt != null) |
    "\(.id)|\(.pricing.prompt | tonumber * 1000000)|\(.pricing.completion | tonumber * 1000000)|\(.context_length)|⭐"' \
    "$TEMP_FILE" | awk -F'|' '{printf "%s|$%.2f|$%.2f|%s|%s\n", $1, $2, $3, $4, $5}' | sort -t'$' -k2 -n >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"

# Budget-Friendly Models
echo "## Budget-Friendly Models (<\$1/M input)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

jq -r '.data[] | 
    select(.pricing.prompt != null) |
    select((.pricing.prompt | tonumber) < 0.000001) |
    select(.id | test("gpt|claude|gemini|kimi|qwen|llama|mistral")) |
    "### \(.id)\n\n**Name:** \(.name)  \n**Input:** $\(.pricing.prompt | tonumber * 1000000)/1M tokens  \n**Output:** $\(.pricing.completion | tonumber * 1000000)/1M tokens  \n**Context:** \(.context_length) tokens  \n**Type:** \(.architecture.modality)\n"' \
    "$TEMP_FILE" >> "$OUTPUT_FILE"

# Mid-Tier Models
echo "## Mid-Tier Models (\$1-5/M input)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

jq -r '.data[] | 
    select(.pricing.prompt != null) |
    select((.pricing.prompt | tonumber) >= 0.000001) |
    select((.pricing.prompt | tonumber) < 0.000005) |
    select(.id | test("gpt|claude|gemini|qwen")) |
    "### \(.id)\n\n**Name:** \(.name)  \n**Input:** $\(.pricing.prompt | tonumber * 1000000)/1M tokens  \n**Output:** $\(.pricing.completion | tonumber * 1000000)/1M tokens  \n**Context:** \(.context_length) tokens  \n**Type:** \(.architecture.modality)\n"' \
    "$TEMP_FILE" >> "$OUTPUT_FILE"

# Premium Models
echo "## Premium Models (>\$5/M input)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

jq -r '.data[] | 
    select(.pricing.prompt != null) |
    select((.pricing.prompt | tonumber) >= 0.000005) |
    select(.id | test("claude|gpt|gemini|opus")) |
    "### \(.id)\n\n**Name:** \(.name)  \n**Input:** $\(.pricing.prompt | tonumber * 1000000)/1M tokens  \n**Output:** $\(.pricing.completion | tonumber * 1000000)/1M tokens  \n**Context:** \(.context_length) tokens  \n**Type:** \(.architecture.modality)\n"' \
    "$TEMP_FILE" | head -100 >> "$OUTPUT_FILE"

# Footer
cat >> "$OUTPUT_FILE" << 'FOOTER'

---

## About This File

This file is automatically generated daily by fetching the latest model information from the [OpenRouter API](https://openrouter.ai/docs/api/api-reference/models/get-models).

**API Endpoint:** `GET https://openrouter.ai/api/v1/models`

**Update Schedule:** Daily at 00:00 UTC

**Data Source:** [OpenRouter Models](https://openrouter.ai/models)

To fetch pricing manually, use:
```bash
./scripts/fetch-openrouter-pricing.sh YOUR_API_KEY
```

Or see [RUNNERS_AND_PRICING.md](RUNNERS_AND_PRICING.md) for complete cost analysis including GitHub Actions costs.
FOOTER

rm "$TEMP_FILE"

echo "Generated $OUTPUT_FILE successfully" >&2
